-- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- PROJECT : Healthcare Analytics 
-- AUTHOR  : Pavani Arudra 
-- FILE_08 : Doctor_Analytics
-- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

use HealthcareDB;

-- Doctor Overview

# 1. Total doctors
select count(*) as 'Total_Doctors'
from Doctors;


# 2. Doctors by department
select
d.Department_Name,
count(doc.Doctor_ID) as 'Total_Doctors'
from Department as d
left join Doctors as doc
on d.Department_ID = doc.Department_ID
group by d.Department_Name
order by Total_Doctors desc;


# 3. Total patients handled by each doctor
select
doc.Doctor_ID,
doc.Doctor_Name,
count(distinct v.Patient_ID) as 'Patients_Handled'
from Doctors as doc
left join Visit as v
on doc.Doctor_ID = v.Doctor_ID
group by doc.Doctor_ID, doc.Doctor_Name
order by Patients_Handled desc;


# 4. Total visits handled by each doctor
select
doc.Doctor_Name,
count(v.Visit_ID) as 'Total_Visits'
from Doctors as doc
left join Visit as v
on doc.Doctor_ID = v.Doctor_ID
group by doc.Doctor_Name
order by Total_Visits desc;


# 5. Top 5 busiest doctors
select
doc.Doctor_Name,
count(v.Visit_ID) as 'Visit_Count'
from Doctors as doc
join Visit as v
on doc.Doctor_ID = v.Doctor_ID
group by doc.Doctor_Name
order by Visit_Count desc
limit 5;


# 6. Doctors with no patient visits
select
doc.Doctor_ID,
doc.Doctor_Name
from Doctors as doc
left join Visit as v
on doc.Doctor_ID = v.Doctor_ID
where v.Visit_ID is null;


-- Revenue Analysis

# 7. Revenue generated by each doctor
select
doc.Doctor_Name,
round(sum(b.Amount_Billed), 2) as 'Revenue'
from Doctors as doc
join Visit as v
on doc.Doctor_ID = v.Doctor_ID
join Billing as b
on v.Visit_ID = b.Visit_ID
group by doc.Doctor_Name
order by Revenue desc;


# 8. Average revenue per doctor
select
round(avg(Revenue), 2) as 'Avg_Revenue'
from
(select
sum(b.Amount_Billed) as Revenue
from Doctors as d
join Visit as v
on d.Doctor_ID = v.Doctor_ID
join Billing as b
on v.Visit_ID = b.Visit_ID
group by d.Doctor_ID
) as T;


-- Experience Analysis

# 9. Average experience by department
select
dep.Department_Name,
round(avg(doc.Years_Of_Experience), 2) as 'Avg_Experience'
from Doctors as doc
join Department as dep
on doc.Department_ID = dep.Department_ID
group by dep.Department_Name;

# 10. Doctors by Speciality
select Speciality , count(*) as 'Total_Doctors'
from Doctors group by Speciality;


-- Treatment Analysis

# 11. Treatments performed by each doctor
select
doc.Doctor_Name,
count(t.Treatment_ID) as 'Treatments'
from Doctors as doc
join Visit as v
on doc.Doctor_ID = v.Doctor_ID
join Treatment as t
on v.Visit_ID = t.Visit_ID
group by doc.Doctor_Name
order by Treatments desc;


# 12. Average treatment cost by doctor
select
doc.Doctor_Name,
round(avg(t.direct_Treatment_Cost), 2) as 'Avg_Treatment_Cost'
from Doctors as doc
join Visit as v
on doc.Doctor_ID = v.Doctor_ID
join Treatment as t
on v.Visit_ID = t.Visit_ID
group by doc.Doctor_Name
order by Avg_Treatment_Cost desc;


-- Department Analysis

# 13. Department with highest visits
select
dep.Department_Name,
count(v.Visit_ID) as 'Visits'
from Department as dep
join Doctors as d
on dep.Department_ID = d.Department_ID
join Visit as v
on d.Doctor_ID = v.Doctor_ID
group by dep.Department_Name
order by Visits desc
limit 1;


-- Performance Summary

# 14. Top doctor by revenue
select
doc.Doctor_Name,
sum(b.Amount_Billed) as 'Revenue'
from Doctors as doc
join Visit as v
on doc.Doctor_ID = v.Doctor_ID
join Billing as b
on v.Visit_ID = b.Visit_ID
group by doc.Doctor_Name
order by Revenue desc
limit 1;


# 15. Doctor performance summary
select
doc.Doctor_Name,
count(distinct v.Patient_ID) as 'Patients',
count(v.Visit_ID) as 'Visits',
round(sum(b.Amount_Billed), 2) as 'Revenue'
from Doctors as doc
left join Visit as v
on doc.Doctor_ID = v.Doctor_ID
left join Billing as b
on v.Visit_ID = b.Visit_ID
group by doc.Doctor_Name
order by Revenue desc;